name: SpoonacularAPIClient
targets:
  SpoonacularAPIClient:
    type: framework
    platform: iOS
    deploymentTarget: "11.0"
    sources: [SpoonacularAPIClient]
    info:
      path: ./Info.plist
      version: 1.1
    settings:
      APPLICATION_EXTENSION_API_ONLY: true
    scheme: {}
    dependencies:
    - carthage: AnyCodable
