//
// AddMealPlanTemplate200ResponseItemsInnerValue.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AddMealPlanTemplate200ResponseItemsInnerValue: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int?
    public var servings: Double?
    public var title: String?
    public var imageType: String?

    public init(id: Int? = nil, servings: Double? = nil, title: String? = nil, imageType: String? = nil) {
        self.id = id
        self.servings = servings
        self.title = title
        self.imageType = imageType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case servings
        case title
        case imageType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(servings, forKey: .servings)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(imageType, forKey: .imageType)
    }
}

