//
// AddMealPlanTemplate200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct AddMealPlanTemplate200Response: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var items: Set<AddMealPlanTemplate200ResponseItemsInner>
    public var publishAsPublic: Bool

    public init(name: String, items: Set<AddMealPlanTemplate200ResponseItemsInner>, publishAsPublic: Bool) {
        self.name = name
        self.items = items
        self.publishAsPublic = publishAsPublic
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case items
        case publishAsPublic
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(items, forKey: .items)
        try container.encode(publishAsPublic, forKey: .publishAsPublic)
    }
}

