//
// AddToShoppingListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct AddToShoppingListRequest: Codable, JSONEncodable, Hashable {

    static let itemRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let aisleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var item: String
    public var aisle: String
    public var parse: Bool

    public init(item: String, aisle: String, parse: Bool) {
        self.item = item
        self.aisle = aisle
        self.parse = parse
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case item
        case aisle
        case parse
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(item, forKey: .item)
        try container.encode(aisle, forKey: .aisle)
        try container.encode(parse, forKey: .parse)
    }
}

