//
// AnalyzeRecipeRequest1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyzeRecipeRequest1: Codable, JSONEncodable, Hashable {

    public var title: String?
    public var servings: Int?
    public var ingredients: [String]?
    public var instructions: String?

    public init(title: String? = nil, servings: Int? = nil, ingredients: [String]? = nil, instructions: String? = nil) {
        self.title = title
        self.servings = servings
        self.ingredients = ingredients
        self.instructions = instructions
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case servings
        case ingredients
        case instructions
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(servings, forKey: .servings)
        try container.encodeIfPresent(ingredients, forKey: .ingredients)
        try container.encodeIfPresent(instructions, forKey: .instructions)
    }
}

