//
// ClassifyGroceryProductRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ClassifyGroceryProductRequest: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var title: String
    public var upc: String
    public var pluCode: String

    public init(title: String, upc: String, pluCode: String) {
        self.title = title
        self.upc = upc
        self.pluCode = pluCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case title
        case upc
        case pluCode = "plu_code"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(title, forKey: .title)
        try container.encode(upc, forKey: .upc)
        try container.encode(pluCode, forKey: .pluCode)
    }
}

