//
// ClassifyGroceryProduct200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ClassifyGroceryProduct200Response: Codable, JSONEncodable, Hashable {

    static let cleanTitleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let categoryRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var cleanTitle: String
    public var image: String
    public var category: String
    public var breadcrumbs: [String]
    public var usdaCode: Int

    public init(cleanTitle: String, image: String, category: String, breadcrumbs: [String], usdaCode: Int) {
        self.cleanTitle = cleanTitle
        self.image = image
        self.category = category
        self.breadcrumbs = breadcrumbs
        self.usdaCode = usdaCode
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cleanTitle
        case image
        case category
        case breadcrumbs
        case usdaCode
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cleanTitle, forKey: .cleanTitle)
        try container.encode(image, forKey: .image)
        try container.encode(category, forKey: .category)
        try container.encode(breadcrumbs, forKey: .breadcrumbs)
        try container.encode(usdaCode, forKey: .usdaCode)
    }
}

