//
// ConnectUserRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ConnectUserRequest: Codable, JSONEncodable, Hashable {

    static let usernameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let firstNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let lastNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let emailRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var username: String
    public var firstName: String
    public var lastName: String
    public var email: String

    public init(username: String, firstName: String, lastName: String, email: String) {
        self.username = username
        self.firstName = firstName
        self.lastName = lastName
        self.email = email
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case firstName
        case lastName
        case email
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(firstName, forKey: .firstName)
        try container.encode(lastName, forKey: .lastName)
        try container.encode(email, forKey: .email)
    }
}

