//
// GenerateShoppingListRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GenerateShoppingListRequest: Codable, JSONEncodable, Hashable {

    /** The username. */
    public var username: String
    /** The start date in the format yyyy-mm-dd. */
    public var startDate: String
    /** The end date in the format yyyy-mm-dd. */
    public var endDate: String
    /** The private hash for the username. */
    public var hash: String

    public init(username: String, startDate: String, endDate: String, hash: String) {
        self.username = username
        self.startDate = startDate
        self.endDate = endDate
        self.hash = hash
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case username
        case startDate = "start-date"
        case endDate = "end-date"
        case hash
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(username, forKey: .username)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
        try container.encode(hash, forKey: .hash)
    }
}

