//
// GenerateMealPlan200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GenerateMealPlan200Response: Codable, JSONEncodable, Hashable {

    public var meals: Set<GetSimilarRecipes200ResponseInner>
    public var nutrients: GenerateMealPlan200ResponseNutrients

    public init(meals: Set<GetSimilarRecipes200ResponseInner>, nutrients: GenerateMealPlan200ResponseNutrients) {
        self.meals = meals
        self.nutrients = nutrients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case meals
        case nutrients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(meals, forKey: .meals)
        try container.encode(nutrients, forKey: .nutrients)
    }
}

