//
// GetConversationSuggests200ResponseSuggests.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetConversationSuggests200ResponseSuggests: Codable, JSONEncodable, Hashable {

    public var _: Set<GetConversationSuggests200ResponseSuggestsInner>

    public init(_: Set<GetConversationSuggests200ResponseSuggestsInner>) {
        self._ = _
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case _
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(_, forKey: ._)
    }
}

