//
// GetDishPairingForWine200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetDishPairingForWine200Response: Codable, JSONEncodable, Hashable {

    static let textRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var pairings: [String]
    public var text: String

    public init(pairings: [String], text: String) {
        self.pairings = pairings
        self.text = text
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case pairings
        case text
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(pairings, forKey: .pairings)
        try container.encode(text, forKey: .text)
    }
}

