//
// GetIngredientSubstitutes200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetIngredientSubstitutes200Response: Codable, JSONEncodable, Hashable {

    static let ingredientRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let messageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var ingredient: String
    public var substitutes: [String]
    public var message: String

    public init(ingredient: String, substitutes: [String], message: String) {
        self.ingredient = ingredient
        self.substitutes = substitutes
        self.message = message
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredient
        case substitutes
        case message
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredient, forKey: .ingredient)
        try container.encode(substitutes, forKey: .substitutes)
        try container.encode(message, forKey: .message)
    }
}

