//
// GetRecipePriceBreakdownByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetRecipePriceBreakdownByID200Response: Codable, JSONEncodable, Hashable {

    public var ingredients: Set<GetRecipePriceBreakdownByID200ResponseIngredientsInner>
    public var totalCost: Double
    public var totalCostPerServing: Double

    public init(ingredients: Set<GetRecipePriceBreakdownByID200ResponseIngredientsInner>, totalCost: Double, totalCostPerServing: Double) {
        self.ingredients = ingredients
        self.totalCost = totalCost
        self.totalCostPerServing = totalCostPerServing
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredients
        case totalCost
        case totalCostPerServing
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(totalCost, forKey: .totalCost)
        try container.encode(totalCostPerServing, forKey: .totalCostPerServing)
    }
}

