//
// GetRecipeInformation200ResponseExtendedIngredientsInnerMeasuresMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecipeInformation200ResponseExtendedIngredientsInnerMeasuresMetric: Codable, JSONEncodable, Hashable {

    static let unitLongRule = StringRule(minLength: 0, maxLength: nil, pattern: nil)
    static let unitShortRule = StringRule(minLength: 0, maxLength: nil, pattern: nil)
    public var amount: Double
    public var unitLong: String
    public var unitShort: String

    public init(amount: Double, unitLong: String, unitShort: String) {
        self.amount = amount
        self.unitLong = unitLong
        self.unitShort = unitShort
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case unitLong
        case unitShort
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(unitLong, forKey: .unitLong)
        try container.encode(unitShort, forKey: .unitShort)
    }
}

