//
// GetShoppingList200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetShoppingList200Response: Codable, JSONEncodable, Hashable {

    public var aisles: Set<GetShoppingList200ResponseAislesInner>
    public var cost: Double
    public var startDate: Double
    public var endDate: Double

    public init(aisles: Set<GetShoppingList200ResponseAislesInner>, cost: Double, startDate: Double, endDate: Double) {
        self.aisles = aisles
        self.cost = cost
        self.startDate = startDate
        self.endDate = endDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aisles
        case cost
        case startDate
        case endDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aisles, forKey: .aisles)
        try container.encode(cost, forKey: .cost)
        try container.encode(startDate, forKey: .startDate)
        try container.encode(endDate, forKey: .endDate)
    }
}

