//
// GuessNutritionByDishName200ResponseCalories.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GuessNutritionByDishName200ResponseCalories: Codable, JSONEncodable, Hashable {

    static let unitRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var confidenceRange95Percent: GuessNutritionByDishName200ResponseCaloriesConfidenceRange95Percent
    public var standardDeviation: Double
    public var unit: String
    public var value: Double

    public init(confidenceRange95Percent: GuessNutritionByDishName200ResponseCaloriesConfidenceRange95Percent, standardDeviation: Double, unit: String, value: Double) {
        self.confidenceRange95Percent = confidenceRange95Percent
        self.standardDeviation = standardDeviation
        self.unit = unit
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case confidenceRange95Percent
        case standardDeviation
        case unit
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(confidenceRange95Percent, forKey: .confidenceRange95Percent)
        try container.encode(standardDeviation, forKey: .standardDeviation)
        try container.encode(unit, forKey: .unit)
        try container.encode(value, forKey: .value)
    }
}

