//
// ImageClassificationByURL200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ImageClassificationByURL200Response: Codable, JSONEncodable, Hashable {

    static let categoryRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var category: String
    public var probability: Double

    public init(category: String, probability: Double) {
        self.category = category
        self.probability = probability
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case category
        case probability
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(category, forKey: .category)
        try container.encode(probability, forKey: .probability)
    }
}

