//
// ImageAnalysisByURL200ResponseNutrition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ImageAnalysisByURL200ResponseNutrition: Codable, JSONEncodable, Hashable {

    public var recipesUsed: Int
    public var calories: ImageAnalysisByURL200ResponseNutritionCalories
    public var fat: ImageAnalysisByURL200ResponseNutritionCalories
    public var protein: ImageAnalysisByURL200ResponseNutritionCalories
    public var carbs: ImageAnalysisByURL200ResponseNutritionCalories

    public init(recipesUsed: Int, calories: ImageAnalysisByURL200ResponseNutritionCalories, fat: ImageAnalysisByURL200ResponseNutritionCalories, protein: ImageAnalysisByURL200ResponseNutritionCalories, carbs: ImageAnalysisByURL200ResponseNutritionCalories) {
        self.recipesUsed = recipesUsed
        self.calories = calories
        self.fat = fat
        self.protein = protein
        self.carbs = carbs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case recipesUsed
        case calories
        case fat
        case protein
        case carbs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(recipesUsed, forKey: .recipesUsed)
        try container.encode(calories, forKey: .calories)
        try container.encode(fat, forKey: .fat)
        try container.encode(protein, forKey: .protein)
        try container.encode(carbs, forKey: .carbs)
    }
}

