//
// ImageAnalysisByURL200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ImageAnalysisByURL200Response: Codable, JSONEncodable, Hashable {

    public var nutrition: ImageAnalysisByURL200ResponseNutrition
    public var category: ImageAnalysisByURL200ResponseCategory
    public var recipes: Set<ImageAnalysisByURL200ResponseRecipesInner>

    public init(nutrition: ImageAnalysisByURL200ResponseNutrition, category: ImageAnalysisByURL200ResponseCategory, recipes: Set<ImageAnalysisByURL200ResponseRecipesInner>) {
        self.nutrition = nutrition
        self.category = category
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nutrition
        case category
        case recipes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nutrition, forKey: .nutrition)
        try container.encode(category, forKey: .category)
        try container.encode(recipes, forKey: .recipes)
    }
}

