//
// IngredientSearch200ResponseResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct IngredientSearch200ResponseResultsInner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int
    public var name: String
    public var image: String

    public init(id: Int, name: String, image: String) {
        self.id = id
        self.name = name
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case name
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(name, forKey: .name)
        try container.encode(image, forKey: .image)
    }
}

