//
// ParseIngredients200ResponseInnerNutritionWeightPerServing.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParseIngredients200ResponseInnerNutritionWeightPerServing: Codable, JSONEncodable, Hashable {

    static let unitRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var amount: Double
    public var unit: String

    public init(amount: Double, unit: String) {
        self.amount = amount
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case amount
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(amount, forKey: .amount)
        try container.encode(unit, forKey: .unit)
    }
}

