//
// QuickAnswer200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct QuickAnswer200Response: Codable, JSONEncodable, Hashable {

    static let answerRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var answer: String
    public var image: String

    public init(answer: String, image: String) {
        self.answer = answer
        self.image = image
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case answer
        case image
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(answer, forKey: .answer)
        try container.encode(image, forKey: .image)
    }
}

