//
// SearchAllFood200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SearchAllFood200Response: Codable, JSONEncodable, Hashable {

    static let queryRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var query: String
    public var totalResults: Int
    public var limit: Int
    public var offset: Int
    public var searchResults: Set<SearchAllFood200ResponseSearchResultsInner>

    public init(query: String, totalResults: Int, limit: Int, offset: Int, searchResults: Set<SearchAllFood200ResponseSearchResultsInner>) {
        self.query = query
        self.totalResults = totalResults
        self.limit = limit
        self.offset = offset
        self.searchResults = searchResults
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case query
        case totalResults
        case limit
        case offset
        case searchResults
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(query, forKey: .query)
        try container.encode(totalResults, forKey: .totalResults)
        try container.encode(limit, forKey: .limit)
        try container.encode(offset, forKey: .offset)
        try container.encode(searchResults, forKey: .searchResults)
    }
}

