//
// SearchMenuItems200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SearchMenuItems200Response: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var menuItems: Set<SearchMenuItems200ResponseMenuItemsInner>
    public var totalMenuItems: Int
    public var type: String
    public var offset: Int
    public var number: Int

    public init(menuItems: Set<SearchMenuItems200ResponseMenuItemsInner>, totalMenuItems: Int, type: String, offset: Int, number: Int) {
        self.menuItems = menuItems
        self.totalMenuItems = totalMenuItems
        self.type = type
        self.offset = offset
        self.number = number
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case menuItems
        case totalMenuItems
        case type
        case offset
        case number
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(menuItems, forKey: .menuItems)
        try container.encode(totalMenuItems, forKey: .totalMenuItems)
        try container.encode(type, forKey: .type)
        try container.encode(offset, forKey: .offset)
        try container.encode(number, forKey: .number)
    }
}

