//
// SearchAllFood200ResponseSearchResultsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchAllFood200ResponseSearchResultsInner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var totalResults: Int
    public var results: Set<SearchAllFood200ResponseSearchResultsInnerResultsInner>?

    public init(name: String, totalResults: Int, results: Set<SearchAllFood200ResponseSearchResultsInnerResultsInner>? = nil) {
        self.name = name
        self.totalResults = totalResults
        self.results = results
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case totalResults
        case results
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(totalResults, forKey: .totalResults)
        try container.encodeIfPresent(results, forKey: .results)
    }
}

