//
// SearchGroceryProductsByUPC200ResponseNutrition.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchGroceryProductsByUPC200ResponseNutrition: Codable, JSONEncodable, Hashable {

    public var nutrients: Set<ParseIngredients200ResponseInnerNutritionNutrientsInner>
    public var caloricBreakdown: ParseIngredients200ResponseInnerNutritionCaloricBreakdown

    public init(nutrients: Set<ParseIngredients200ResponseInnerNutritionNutrientsInner>, caloricBreakdown: ParseIngredients200ResponseInnerNutritionCaloricBreakdown) {
        self.nutrients = nutrients
        self.caloricBreakdown = caloricBreakdown
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case nutrients
        case caloricBreakdown
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(nutrients, forKey: .nutrients)
        try container.encode(caloricBreakdown, forKey: .caloricBreakdown)
    }
}

