//
// TalkToChatbot200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct TalkToChatbot200Response: Codable, JSONEncodable, Hashable {

    static let answerTextRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var answerText: String
    public var media: [AnyCodable]

    public init(answerText: String, media: [AnyCodable]) {
        self.answerText = answerText
        self.media = media
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case answerText
        case media
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(answerText, forKey: .answerText)
        try container.encode(media, forKey: .media)
    }
}

