//
// AnalyzeARecipeSearchQuery200ResponseDishesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyzeARecipeSearchQuery200ResponseDishesInner: Codable, JSONEncodable, Hashable {

    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var image: String
    public var name: String

    public init(image: String, name: String) {
        self.image = image
        self.name = name
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case name
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(name, forKey: .name)
    }
}

