//
// AnalyzeARecipeSearchQuery200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct AnalyzeARecipeSearchQuery200Response: Codable, JSONEncodable, Hashable {

    public var dishes: Set<AnalyzeARecipeSearchQuery200ResponseDishesInner>
    public var ingredients: Set<AnalyzeARecipeSearchQuery200ResponseIngredientsInner>
    public var cuisines: [String]
    public var modifiers: [String]

    public init(dishes: Set<AnalyzeARecipeSearchQuery200ResponseDishesInner>, ingredients: Set<AnalyzeARecipeSearchQuery200ResponseIngredientsInner>, cuisines: [String], modifiers: [String]) {
        self.dishes = dishes
        self.ingredients = ingredients
        self.cuisines = cuisines
        self.modifiers = modifiers
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case dishes
        case ingredients
        case cuisines
        case modifiers
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(dishes, forKey: .dishes)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(cuisines, forKey: .cuisines)
        try container.encode(modifiers, forKey: .modifiers)
    }
}

