//
// DetectFoodInText200ResponseAnnotationsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct DetectFoodInText200ResponseAnnotationsInner: Codable, JSONEncodable, Hashable {

    static let annotationRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let tagRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var annotation: String
    public var image: String
    public var tag: String

    public init(annotation: String, image: String, tag: String) {
        self.annotation = annotation
        self.image = image
        self.tag = tag
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case annotation
        case image
        case tag
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(annotation, forKey: .annotation)
        try container.encode(image, forKey: .image)
        try container.encode(tag, forKey: .tag)
    }
}

