//
// GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInner: Codable, JSONEncodable, Hashable {

    static let stepRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var number: Double
    public var step: String
    public var ingredients: Set<GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner>?
    public var equipment: Set<GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner>?

    public init(number: Double, step: String, ingredients: Set<GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner>? = nil, equipment: Set<GetAnalyzedRecipeInstructions200ResponseParsedInstructionsInnerStepsInnerIngredientsInner>? = nil) {
        self.number = number
        self.step = step
        self.ingredients = ingredients
        self.equipment = equipment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case step
        case ingredients
        case equipment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(step, forKey: .step)
        try container.encodeIfPresent(ingredients, forKey: .ingredients)
        try container.encodeIfPresent(equipment, forKey: .equipment)
    }
}

