//
// GetComparableProducts200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetComparableProducts200Response: Codable, JSONEncodable, Hashable {

    public var comparableProducts: GetComparableProducts200ResponseComparableProducts

    public init(comparableProducts: GetComparableProducts200ResponseComparableProducts) {
        self.comparableProducts = comparableProducts
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case comparableProducts
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(comparableProducts, forKey: .comparableProducts)
    }
}

