//
// GetProductInformation200ResponseIngredientsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetProductInformation200ResponseIngredientsInner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var description: AnyCodable?
    public var safetyLevel: AnyCodable?

    public init(name: String, description: AnyCodable? = nil, safetyLevel: AnyCodable? = nil) {
        self.name = name
        self.description = description
        self.safetyLevel = safetyLevel
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case description
        case safetyLevel = "safety_level"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(safetyLevel, forKey: .safetyLevel)
    }
}

