//
// GetRecipeIngredientsByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetRecipeIngredientsByID200Response: Codable, JSONEncodable, Hashable {

    public var ingredients: Set<GetRecipeIngredientsByID200ResponseIngredientsInner>

    public init(ingredients: Set<GetRecipeIngredientsByID200ResponseIngredientsInner>) {
        self.ingredients = ingredients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredients, forKey: .ingredients)
    }
}

