//
// GetRecipeTasteByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetRecipeTasteByID200Response: Codable, JSONEncodable, Hashable {

    public var sweetness: Double
    public var saltiness: Double
    public var sourness: Double
    public var bitterness: Double
    public var savoriness: Double
    public var fattiness: Double
    public var spiciness: Double

    public init(sweetness: Double, saltiness: Double, sourness: Double, bitterness: Double, savoriness: Double, fattiness: Double, spiciness: Double) {
        self.sweetness = sweetness
        self.saltiness = saltiness
        self.sourness = sourness
        self.bitterness = bitterness
        self.savoriness = savoriness
        self.fattiness = fattiness
        self.spiciness = spiciness
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case sweetness
        case saltiness
        case sourness
        case bitterness
        case savoriness
        case fattiness
        case spiciness
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(sweetness, forKey: .sweetness)
        try container.encode(saltiness, forKey: .saltiness)
        try container.encode(sourness, forKey: .sourness)
        try container.encode(bitterness, forKey: .bitterness)
        try container.encode(savoriness, forKey: .savoriness)
        try container.encode(fattiness, forKey: .fattiness)
        try container.encode(spiciness, forKey: .spiciness)
    }
}

