//
// GetRecipePriceBreakdownByID200ResponseIngredientsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecipePriceBreakdownByID200ResponseIngredientsInner: Codable, JSONEncodable, Hashable {

    static let imageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var image: String
    public var name: String
    public var price: Double
    public var amount: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmount?

    public init(image: String, name: String, price: Double, amount: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmount? = nil) {
        self.image = image
        self.name = name
        self.price = price
        self.amount = amount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case image
        case name
        case price
        case amount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(image, forKey: .image)
        try container.encode(name, forKey: .name)
        try container.encode(price, forKey: .price)
        try container.encodeIfPresent(amount, forKey: .amount)
    }
}

