//
// GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric: Codable, JSONEncodable, Hashable {

    static let unitRule = StringRule(minLength: 0, maxLength: nil, pattern: nil)
    public var unit: String
    public var value: Double

    public init(unit: String, value: Double) {
        self.unit = unit
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case unit
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(unit, forKey: .unit)
        try container.encode(value, forKey: .value)
    }
}

