//
// GetSimilarRecipes200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetSimilarRecipes200ResponseInner: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let sourceUrlRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int
    public var title: String
    public var imageType: String
    public var readyInMinutes: Int
    public var servings: Double
    public var sourceUrl: String

    public init(id: Int, title: String, imageType: String, readyInMinutes: Int, servings: Double, sourceUrl: String) {
        self.id = id
        self.title = title
        self.imageType = imageType
        self.readyInMinutes = readyInMinutes
        self.servings = servings
        self.sourceUrl = sourceUrl
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case imageType
        case readyInMinutes
        case servings
        case sourceUrl
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(imageType, forKey: .imageType)
        try container.encode(readyInMinutes, forKey: .readyInMinutes)
        try container.encode(servings, forKey: .servings)
        try container.encode(sourceUrl, forKey: .sourceUrl)
    }
}

