//
// GetShoppingList200ResponseAislesInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetShoppingList200ResponseAislesInner: Codable, JSONEncodable, Hashable {

    static let aisleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var aisle: String
    public var items: Set<GetShoppingList200ResponseAislesInnerItemsInner>?

    public init(aisle: String, items: Set<GetShoppingList200ResponseAislesInnerItemsInner>? = nil) {
        self.aisle = aisle
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case aisle
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(aisle, forKey: .aisle)
        try container.encodeIfPresent(items, forKey: .items)
    }
}

