//
// GetWineDescription200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetWineDescription200Response: Codable, JSONEncodable, Hashable {

    static let wineDescriptionRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var wineDescription: String

    public init(wineDescription: String) {
        self.wineDescription = wineDescription
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case wineDescription
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(wineDescription, forKey: .wineDescription)
    }
}

