//
// MapIngredientsToGroceryProductsRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct MapIngredientsToGroceryProductsRequest: Codable, JSONEncodable, Hashable {

    public var ingredients: [String]
    public var servings: Double

    public init(ingredients: [String], servings: Double) {
        self.ingredients = ingredients
        self.servings = servings
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case ingredients
        case servings
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(servings, forKey: .servings)
    }
}

