//
// AddToMealPlanRequest1.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct AddToMealPlanRequest1: Codable, JSONEncodable, Hashable {

    static let typeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var date: Double
    public var slot: Int
    public var position: Int
    public var type: String
    public var value: AddToMealPlanRequest1Value

    public init(date: Double, slot: Int, position: Int, type: String, value: AddToMealPlanRequest1Value) {
        self.date = date
        self.slot = slot
        self.position = position
        self.type = type
        self.value = value
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case date
        case slot
        case position
        case type
        case value
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(date, forKey: .date)
        try container.encode(slot, forKey: .slot)
        try container.encode(position, forKey: .position)
        try container.encode(type, forKey: .type)
        try container.encode(value, forKey: .value)
    }
}

