//
// AnalyzeRecipeRequest.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct AnalyzeRecipeRequest: Codable, JSONEncodable, Hashable {

    /** The input language, either \"en\" or \"de\". */
    public var language: String?
    /** Whether nutrition data should be added to correctly parsed ingredients. */
    public var includeNutrition: Bool?
    /** Whether taste data should be added to correctly parsed ingredients. */
    public var includeTaste: Bool?

    public init(language: String? = nil, includeNutrition: Bool? = nil, includeTaste: Bool? = nil) {
        self.language = language
        self.includeNutrition = includeNutrition
        self.includeTaste = includeTaste
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case language
        case includeNutrition
        case includeTaste
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(language, forKey: .language)
        try container.encodeIfPresent(includeNutrition, forKey: .includeNutrition)
        try container.encodeIfPresent(includeTaste, forKey: .includeTaste)
    }
}

