//
// GetMealPlanTemplates200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetMealPlanTemplates200Response: Codable, JSONEncodable, Hashable {

    public var templates: Set<GetAnalyzedRecipeInstructions200ResponseIngredientsInner>

    public init(templates: Set<GetAnalyzedRecipeInstructions200ResponseIngredientsInner>) {
        self.templates = templates
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case templates
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(templates, forKey: .templates)
    }
}

