//
// GetRecipeNutritionWidgetByID200ResponseBadInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecipeNutritionWidgetByID200ResponseBadInner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let amountRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var amount: String
    public var indented: Bool
    public var percentOfDailyNeeds: Double

    public init(name: String, amount: String, indented: Bool, percentOfDailyNeeds: Double) {
        self.name = name
        self.amount = amount
        self.indented = indented
        self.percentOfDailyNeeds = percentOfDailyNeeds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case amount
        case indented
        case percentOfDailyNeeds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(amount, forKey: .amount)
        try container.encode(indented, forKey: .indented)
        try container.encode(percentOfDailyNeeds, forKey: .percentOfDailyNeeds)
    }
}

