//
// GetRecipeEquipmentByID200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetRecipeEquipmentByID200Response: Codable, JSONEncodable, Hashable {

    public var equipment: Set<GetRecipeEquipmentByID200ResponseEquipmentInner>

    public init(equipment: Set<GetRecipeEquipmentByID200ResponseEquipmentInner>) {
        self.equipment = equipment
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case equipment
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(equipment, forKey: .equipment)
    }
}

