//
// GuessNutritionByDishName200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GuessNutritionByDishName200Response: Codable, JSONEncodable, Hashable {

    public var calories: GuessNutritionByDishName200ResponseCalories
    public var carbs: GuessNutritionByDishName200ResponseCalories
    public var fat: GuessNutritionByDishName200ResponseCalories
    public var protein: GuessNutritionByDishName200ResponseCalories
    public var recipesUsed: Int

    public init(calories: GuessNutritionByDishName200ResponseCalories, carbs: GuessNutritionByDishName200ResponseCalories, fat: GuessNutritionByDishName200ResponseCalories, protein: GuessNutritionByDishName200ResponseCalories, recipesUsed: Int) {
        self.calories = calories
        self.carbs = carbs
        self.fat = fat
        self.protein = protein
        self.recipesUsed = recipesUsed
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case calories
        case carbs
        case fat
        case protein
        case recipesUsed
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(calories, forKey: .calories)
        try container.encode(carbs, forKey: .carbs)
        try container.encode(fat, forKey: .fat)
        try container.encode(protein, forKey: .protein)
        try container.encode(recipesUsed, forKey: .recipesUsed)
    }
}

