//
// MapIngredientsToGroceryProducts200ResponseInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct MapIngredientsToGroceryProducts200ResponseInner: Codable, JSONEncodable, Hashable {

    static let originalRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let originalNameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let ingredientImageRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var original: String
    public var originalName: String
    public var ingredientImage: String
    public var meta: [String]
    public var products: Set<MapIngredientsToGroceryProducts200ResponseInnerProductsInner>

    public init(original: String, originalName: String, ingredientImage: String, meta: [String], products: Set<MapIngredientsToGroceryProducts200ResponseInnerProductsInner>) {
        self.original = original
        self.originalName = originalName
        self.ingredientImage = ingredientImage
        self.meta = meta
        self.products = products
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case original
        case originalName
        case ingredientImage
        case meta
        case products
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(original, forKey: .original)
        try container.encode(originalName, forKey: .originalName)
        try container.encode(ingredientImage, forKey: .ingredientImage)
        try container.encode(meta, forKey: .meta)
        try container.encode(products, forKey: .products)
    }
}

