//
// SearchRestaurants200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchRestaurants200Response: Codable, JSONEncodable, Hashable {

    public var restaurants: [SearchRestaurants200ResponseRestaurantsInner]?

    public init(restaurants: [SearchRestaurants200ResponseRestaurantsInner]? = nil) {
        self.restaurants = restaurants
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case restaurants
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(restaurants, forKey: .restaurants)
    }
}

