//
// SearchGroceryProductsByUPC200ResponseServings.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchGroceryProductsByUPC200ResponseServings: Codable, JSONEncodable, Hashable {

    static let unitRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var number: Double
    public var size: Double
    public var unit: String

    public init(number: Double, size: Double, unit: String) {
        self.number = number
        self.size = size
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case size
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(size, forKey: .size)
        try container.encode(unit, forKey: .unit)
    }
}

