//
// SearchCustomFoods200ResponseCustomFoodsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchCustomFoods200ResponseCustomFoodsInner: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageUrlRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int
    public var title: String
    public var servings: Double
    public var imageUrl: String
    public var price: Double

    public init(id: Int, title: String, servings: Double, imageUrl: String, price: Double) {
        self.id = id
        self.title = title
        self.servings = servings
        self.imageUrl = imageUrl
        self.price = price
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case servings
        case imageUrl
        case price
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(servings, forKey: .servings)
        try container.encode(imageUrl, forKey: .imageUrl)
        try container.encode(price, forKey: .price)
    }
}

