//
// ClassifyCuisine200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ClassifyCuisine200Response: Codable, JSONEncodable, Hashable {

    static let cuisineRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var cuisine: String
    public var cuisines: [String]
    public var confidence: Double

    public init(cuisine: String, cuisines: [String], confidence: Double) {
        self.cuisine = cuisine
        self.cuisines = cuisines
        self.confidence = confidence
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case cuisine
        case cuisines
        case confidence
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(cuisine, forKey: .cuisine)
        try container.encode(cuisines, forKey: .cuisines)
        try container.encode(confidence, forKey: .confidence)
    }
}

