//
// ComputeGlycemicLoad200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct ComputeGlycemicLoad200Response: Codable, JSONEncodable, Hashable {

    public var totalGlycemicLoad: Double
    public var ingredients: Set<ComputeGlycemicLoad200ResponseIngredientsInner>

    public init(totalGlycemicLoad: Double, ingredients: Set<ComputeGlycemicLoad200ResponseIngredientsInner>) {
        self.totalGlycemicLoad = totalGlycemicLoad
        self.ingredients = ingredients
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalGlycemicLoad
        case ingredients
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalGlycemicLoad, forKey: .totalGlycemicLoad)
        try container.encode(ingredients, forKey: .ingredients)
    }
}

