//
// GetConversationSuggests200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct GetConversationSuggests200Response: Codable, JSONEncodable, Hashable {

    public var suggests: GetConversationSuggests200ResponseSuggests
    public var words: [AnyCodable]

    public init(suggests: GetConversationSuggests200ResponseSuggests, words: [AnyCodable]) {
        self.suggests = suggests
        self.words = words
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case suggests
        case words
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(suggests, forKey: .suggests)
        try container.encode(words, forKey: .words)
    }
}

