//
// GetMealPlanWeek200ResponseDaysInnerNutritionSummaryNutrientsInner.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetMealPlanWeek200ResponseDaysInnerNutritionSummaryNutrientsInner: Codable, JSONEncodable, Hashable {

    static let nameRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let unitRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var name: String
    public var amount: Double
    public var unit: String
    public var percentDailyNeeds: Double

    public init(name: String, amount: Double, unit: String, percentDailyNeeds: Double) {
        self.name = name
        self.amount = amount
        self.unit = unit
        self.percentDailyNeeds = percentDailyNeeds
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case name
        case amount
        case unit
        case percentDailyNeeds
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(name, forKey: .name)
        try container.encode(amount, forKey: .amount)
        try container.encode(unit, forKey: .unit)
        try container.encode(percentDailyNeeds, forKey: .percentDailyNeeds)
    }
}

