//
// GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmount.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmount: Codable, JSONEncodable, Hashable {

    public var metric: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric
    public var us: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric

    public init(metric: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric, us: GetRecipePriceBreakdownByID200ResponseIngredientsInnerAmountMetric) {
        self.metric = metric
        self.us = us
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case metric
        case us
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(metric, forKey: .metric)
        try container.encode(us, forKey: .us)
    }
}

