//
// ParseIngredients200ResponseInnerNutritionCaloricBreakdown.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParseIngredients200ResponseInnerNutritionCaloricBreakdown: Codable, JSONEncodable, Hashable {

    public var percentProtein: Double
    public var percentFat: Double
    public var percentCarbs: Double

    public init(percentProtein: Double, percentFat: Double, percentCarbs: Double) {
        self.percentProtein = percentProtein
        self.percentFat = percentFat
        self.percentCarbs = percentCarbs
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case percentProtein
        case percentFat
        case percentCarbs
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(percentProtein, forKey: .percentProtein)
        try container.encode(percentFat, forKey: .percentFat)
        try container.encode(percentCarbs, forKey: .percentCarbs)
    }
}

