//
// ParseIngredients200ResponseInnerEstimatedCost.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct ParseIngredients200ResponseInnerEstimatedCost: Codable, JSONEncodable, Hashable {

    static let unitRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var value: Double
    public var unit: String

    public init(value: Double, unit: String) {
        self.value = value
        self.unit = unit
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case value
        case unit
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(value, forKey: .value)
        try container.encode(unit, forKey: .unit)
    }
}

