//
// SearchGroceryProductsByUPC200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SearchGroceryProductsByUPC200Response: Codable, JSONEncodable, Hashable {

    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let generatedTextRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let imageTypeRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let ingredientListRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int
    public var title: String
    public var badges: [String]
    public var importantBadges: [String]
    public var breadcrumbs: [String]
    public var generatedText: String
    public var imageType: String
    public var ingredientList: String
    public var ingredients: Set<SearchGroceryProductsByUPC200ResponseIngredientsInner>
    public var likes: Double
    public var nutrition: SearchGroceryProductsByUPC200ResponseNutrition
    public var price: Double
    public var servings: SearchGroceryProductsByUPC200ResponseServings
    public var spoonacularScore: Double
    public var ingredientCount: Int?

    public init(id: Int, title: String, badges: [String], importantBadges: [String], breadcrumbs: [String], generatedText: String, imageType: String, ingredientList: String, ingredients: Set<SearchGroceryProductsByUPC200ResponseIngredientsInner>, likes: Double, nutrition: SearchGroceryProductsByUPC200ResponseNutrition, price: Double, servings: SearchGroceryProductsByUPC200ResponseServings, spoonacularScore: Double, ingredientCount: Int? = nil) {
        self.id = id
        self.title = title
        self.badges = badges
        self.importantBadges = importantBadges
        self.breadcrumbs = breadcrumbs
        self.generatedText = generatedText
        self.imageType = imageType
        self.ingredientList = ingredientList
        self.ingredients = ingredients
        self.likes = likes
        self.nutrition = nutrition
        self.price = price
        self.servings = servings
        self.spoonacularScore = spoonacularScore
        self.ingredientCount = ingredientCount
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case title
        case badges
        case importantBadges
        case breadcrumbs
        case generatedText
        case imageType
        case ingredientList
        case ingredients
        case likes
        case nutrition
        case price
        case servings
        case spoonacularScore
        case ingredientCount
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(title, forKey: .title)
        try container.encode(badges, forKey: .badges)
        try container.encode(importantBadges, forKey: .importantBadges)
        try container.encode(breadcrumbs, forKey: .breadcrumbs)
        try container.encode(generatedText, forKey: .generatedText)
        try container.encode(imageType, forKey: .imageType)
        try container.encode(ingredientList, forKey: .ingredientList)
        try container.encode(ingredients, forKey: .ingredients)
        try container.encode(likes, forKey: .likes)
        try container.encode(nutrition, forKey: .nutrition)
        try container.encode(price, forKey: .price)
        try container.encode(servings, forKey: .servings)
        try container.encode(spoonacularScore, forKey: .spoonacularScore)
        try container.encodeIfPresent(ingredientCount, forKey: .ingredientCount)
    }
}

