//
// SearchSiteContent200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SearchSiteContent200Response: Codable, JSONEncodable, Hashable {

    public var articles: Set<SearchSiteContent200ResponseArticlesInner>
    public var groceryProducts: Set<SearchSiteContent200ResponseGroceryProductsInner>
    public var menuItems: Set<SearchSiteContent200ResponseGroceryProductsInner>
    public var recipes: Set<SearchSiteContent200ResponseGroceryProductsInner>

    public init(articles: Set<SearchSiteContent200ResponseArticlesInner>, groceryProducts: Set<SearchSiteContent200ResponseGroceryProductsInner>, menuItems: Set<SearchSiteContent200ResponseGroceryProductsInner>, recipes: Set<SearchSiteContent200ResponseGroceryProductsInner>) {
        self.articles = articles
        self.groceryProducts = groceryProducts
        self.menuItems = menuItems
        self.recipes = recipes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case articles = "Articles"
        case groceryProducts = "Grocery Products"
        case menuItems = "Menu Items"
        case recipes = "Recipes"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(articles, forKey: .articles)
        try container.encode(groceryProducts, forKey: .groceryProducts)
        try container.encode(menuItems, forKey: .menuItems)
        try container.encode(recipes, forKey: .recipes)
    }
}

