//
// SearchRestaurants200ResponseRestaurantsInnerLocalHours.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

public struct SearchRestaurants200ResponseRestaurantsInnerLocalHours: Codable, JSONEncodable, Hashable {

    public var operational: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational?
    public var delivery: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational?
    public var pickup: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational?
    public var dineIn: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational?

    public init(operational: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational? = nil, delivery: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational? = nil, pickup: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational? = nil, dineIn: SearchRestaurants200ResponseRestaurantsInnerLocalHoursOperational? = nil) {
        self.operational = operational
        self.delivery = delivery
        self.pickup = pickup
        self.dineIn = dineIn
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case operational
        case delivery
        case pickup
        case dineIn = "dine_in"
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(operational, forKey: .operational)
        try container.encodeIfPresent(delivery, forKey: .delivery)
        try container.encodeIfPresent(pickup, forKey: .pickup)
        try container.encodeIfPresent(dineIn, forKey: .dineIn)
    }
}

