//
// SummarizeRecipe200Response.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation
#if canImport(AnyCodable)
import AnyCodable
#endif

/**  */
public struct SummarizeRecipe200Response: Codable, JSONEncodable, Hashable {

    static let summaryRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    static let titleRule = StringRule(minLength: 1, maxLength: nil, pattern: nil)
    public var id: Int
    public var summary: String
    public var title: String

    public init(id: Int, summary: String, title: String) {
        self.id = id
        self.summary = summary
        self.title = title
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case summary
        case title
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(id, forKey: .id)
        try container.encode(summary, forKey: .summary)
        try container.encode(title, forKey: .title)
    }
}

